matrix:
  include:
    # Java build
    - language: java
      jdk: oraclejdk8
    
    # Python build
    - language: python
      python: 2.7
      
    # Golang build
    - language: golang
      golang: 1.8