sudo: enabled

matrix:
  include:
    # Java build
    - language: java
      jdk: oraclejdk8
      before_install:
        - echo "pass" #TODO.
      install:
        - echo "pass" #TODO.
      script:
        - echo "pass" #TODO.
    
    # Python build
    - language: python
      python:
        - 2.7
        - 3.6
      before_install:
        - sudo pip install -r requirements.txt;
        - sudo pip install grpcio;
      install:
        - echo "pass" # make -f Makefile
      script:
        - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            python tf-demonstration/prod-client-gui-mock/run_all_tests.py;
          fi
        - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
            python3 tf-demonstration/prod-client-gui-mock/run_all_tests.py;
          fi
      
    # Golang build
    - language: go
      go:
        - 1.8
        - 1.9
        - 1.10
      before_install:
        - echo "pass" #TODO.
      install:
        - echo "pass" #TODO.
      script:
        - echo "pass" #TODO.