sudo: enabled

matrix:
  include:
    # # Java build
    # - language: java
    #   jdk: oraclejdk8
    
    # Python build
    - language: python
      python: 2.7
      
    # # Golang build
    # - language: golang
    #   golang: 1.8

# 
before_install:
  - sudo pip install r requirements.txt
        
install:
  - echo "pass"

script:
  - python tf-demonstration/prod-client-gui-mock/tests/run_all_tests.py