sudo: enabled

matrix:
  include:
    # Java build
    - language: java
      jdk: oraclejdk8
    
    # Python build
    - language: python
      python: 2.7
      
    - language: python
      python: 3.6
      
    # Golang build
    - language: golang
      golang: 1.8

# 
before_install:
  # For the python builds, install the requirements.
  - sudo pip install -r requirements.txt
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     sudo pip install -r requirements.txt;
  #   fi
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
  #     sudo pip3 install -r requirements.txt;
  #   fi
        
install:
  - echo "pass"

script:
  # Run the python unit tests.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      python tf-demonstration/prod-client-gui-mock/tests/run_all_tests.py;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      python3 tf-demonstration/prod-client-gui-mock/tests/run_all_tests.py;
    fi